// src/components/talent/AssessmentReports.tsx
// Printable A4 reports: one per candidate, and a consolidated ranked report
// per exam schedule. Percentiles are WITHIN THIS INTAKE (not national norms).

import { Dialog, DialogContent } from "@/components/ui/dialog";
import { Printer, X, Download } from "lucide-react";
import { COGNITIVE_SECTIONS, SECTION_LABELS } from "@/lib/testGenerators";
import { RISK_META, TYPE_LABEL, band, cohortPercentile, type AttemptSummary, type Schedule, type Trainee } from "@/hooks/useTalent";

export const TRAITS: Record<string, { label: string; high: string; low: string; lowIsRisk: boolean }> = {
  conscientiousness: { label: "Conscientiousness", high: "organised, thorough and dependable", low: "flexible but may overlook detail or deadlines", lowIsRisk: true },
  extraversion: { label: "Extraversion", high: "outgoing, sociable and comfortable in teams", low: "reserved and suited to independent work", lowIsRisk: false },
  agreeableness: { label: "Service Orientation", high: "cooperative, considerate and service-minded", low: "direct and competitive; may come across as abrasive", lowIsRisk: true },
  stability: { label: "Adjustment", high: "calm and resilient under pressure", low: "prone to worry and may struggle under pressure", lowIsRisk: true },
  openness: { label: "Openness to Experience", high: "curious, keen to learn and adaptable", low: "practical and prefers proven methods", lowIsRisk: false },
};

const fmtDate = (d?: string | null) => (d ? new Date(d).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" }) : "—");

function PrintFrame({ id, title, landscape, open, onClose, onCsv, children }: { id: string; title: string; landscape?: boolean; open: boolean; onClose: () => void; onCsv?: () => void; children: React.ReactNode }) {
  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className={`${landscape ? "max-w-[1180px]" : "max-w-[880px]"} max-h-[92vh] overflow-y-auto p-0`} aria-describedby={undefined}>
        <style>{`@media print { body * { visibility: hidden !important; } #${id}, #${id} * { visibility: visible !important; } #${id} { position: absolute; inset: 0; width: 100%; padding: 0 !important; } @page { size: A4 ${landscape ? "landscape" : "portrait"}; margin: 1.3cm; } }`}</style>
        <div className="flex items-center justify-between px-6 py-3 border-b border-[#DDDDDD] print:hidden sticky top-0 bg-white z-10">
          <span className="text-[14px] font-semibold text-black">{title}</span>
          <div className="flex items-center gap-2">
            {onCsv && <button onClick={onCsv} className="h-8 px-3 rounded-[4px] border border-[#999] text-[12px] font-semibold flex items-center gap-1.5"><Download className="w-3.5 h-3.5" /> CSV</button>}
            <button onClick={() => window.print()} className="h-8 px-3 rounded-[4px] bg-[#EDC817] text-black text-[12px] font-semibold flex items-center gap-1.5"><Printer className="w-3.5 h-3.5" /> Print / Save as PDF</button>
            <button onClick={onClose} className="w-8 h-8 flex items-center justify-center rounded-md text-[#525252] hover:bg-[#FAFAFA]"><X className="w-4 h-4" /></button>
          </div>
        </div>
        <div id={id} className="px-10 py-8 bg-white text-black" style={{ fontFamily: "'Plus Jakarta Sans', sans-serif" }}>
          <div className="flex items-center justify-between pb-4 mb-6 border-b-4 border-[#EDC817]">
            <img src="/magaya_logo.png" alt="Magaya Mining" className="h-[46px] w-auto" />
            <div className="text-right text-[11px] text-[#525252]"><div className="text-[13px] font-bold text-black">Magaya Mining (Private) Limited</div><div>Human Resources — Talent Programmes</div><div className="font-semibold text-[#B91C1C]">CONFIDENTIAL</div></div>
          </div>
          {children}
          <div className="mt-8 pt-3 border-t border-[#DDDDDD] text-[10px] text-[#6B6B6B] leading-relaxed">
            Assessment results must not be used as the sole basis for a selection decision; combine them with interviews, academic records and references.
            Percentiles compare the candidate with others in the same intake, not with national norms, and become more reliable as intakes grow.
            Generated by Magaya ELMS on {fmtDate(new Date().toISOString())}. Do not share this report with the candidate.
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}

function Bar({ value, color = "#EDC817" }: { value: number; color?: string }) {
  return <div className="h-3 bg-[#EEEEEE] rounded-sm overflow-hidden w-full"><div className="h-full" style={{ width: `${Math.max(2, Math.min(100, value))}%`, background: color }} /></div>;
}

export function narrative(a: AttemptSummary) {
  const strengths: string[] = [], development: string[] = [];
  for (const s of COGNITIVE_SECTIONS) {
    const p = a.section_scores?.[s]?.pct; if (p === undefined) continue;
    if (p >= 75) strengths.push(`Strong ${SECTION_LABELS[s].toLowerCase()} (${p}%).`);
    if (p < 40) development.push(`May need support with ${SECTION_LABELS[s].toLowerCase()} tasks (${p}%).`);
  }
  for (const [t, v] of Object.entries(a.trait_scores ?? {})) {
    const m = TRAITS[t]; if (!m) continue;
    if (v >= 70) strengths.push(`Appears ${m.high}.`);
    if (v <= 30) (m.lowIsRisk ? development : strengths).push(`Appears ${m.low}.`);
  }
  return { strengths, development };
}

// ====================== Candidate report ======================
export function CandidateReport({ attempt, trainee, schedule, cohort, open, onClose }: { attempt: AttemptSummary; trainee: Trainee; schedule: Schedule; cohort: AttemptSummary[]; open: boolean; onClose: () => void }) {
  const done = cohort.filter((c) => c.status === "submitted");
  const overallPct = cohortPercentile(attempt.weighted_score ?? 0, done.map((c) => c.weighted_score ?? 0));
  const traitAvg = Object.values(attempt.trait_scores ?? {}); const personality = traitAvg.length ? Math.round(traitAvg.reduce((s, x) => s + x, 0) / traitAvg.length) : null;
  const { strengths, development } = narrative(attempt);
  const risk = RISK_META[attempt.risk ?? "high"];
  return (
    <PrintFrame id="candidate-report" title={`Assessment report — ${trainee.full_name}`} open={open} onClose={onClose}>
      <h1 className="text-[18px] font-bold tracking-wide">CONFIDENTIAL ASSESSMENT REPORT</h1>
      <table className="w-full text-[12px] mt-3 mb-6 border border-[#DDDDDD]"><tbody>
        {[["Candidate", trainee.full_name, "Programme", TYPE_LABEL[trainee.trainee_type]], ["Institution", trainee.institution ?? "—", "Field of study", trainee.programme ?? "—"], ["Assessment", schedule.name, "Completed", fmtDate(attempt.submitted_at)], ["Test form", `Form ${attempt.form_code}`, "Cohort size", `${done.length} candidates`]].map((r) => (
          <tr key={r[0]} className="border-b border-[#DDDDDD] last:border-0"><td className="bg-[#FAFAFA] font-semibold px-3 py-1.5 w-[17%]">{r[0]}</td><td className="px-3 py-1.5 w-[33%]">{r[1]}</td><td className="bg-[#FAFAFA] font-semibold px-3 py-1.5 w-[17%]">{r[2]}</td><td className="px-3 py-1.5">{r[3]}</td></tr>))}
      </tbody></table>

      <div className="text-[12px] font-bold uppercase tracking-[0.06em] border-b-2 border-[#EDC817] pb-1 mb-3">Profile summary</div>
      <div className="space-y-2 mb-6 text-[12px]">
        <div className="grid grid-cols-[180px_1fr_60px] items-center gap-3"><span className="font-semibold">Cognitive ability (weighted)</span><Bar value={attempt.weighted_score ?? 0} color="#000" /><span className="text-right font-bold">{attempt.weighted_score ?? 0}</span></div>
        {personality !== null && <div className="grid grid-cols-[180px_1fr_60px] items-center gap-3"><span className="font-semibold">Personality (average)</span><Bar value={personality} /><span className="text-right font-bold">{personality}</span></div>}
        <div className="grid grid-cols-[180px_1fr_60px] items-center gap-3"><span className="font-semibold">Standing in this intake</span><Bar value={overallPct} color="#6B6B6B" /><span className="text-right font-bold">{overallPct}th</span></div>
      </div>

      <div className="text-[12px] font-bold uppercase tracking-[0.06em] border-b-2 border-[#EDC817] pb-1 mb-3">Cognitive ability</div>
      <table className="w-full text-[12px] mb-6 border border-[#DDDDDD]">
        <thead><tr className="bg-black text-white"><th className="text-left px-3 py-1.5">Test</th><th className="px-3 py-1.5">Score</th><th className="px-3 py-1.5">Weight</th><th className="px-3 py-1.5 w-[30%]">Intake percentile</th><th className="text-left px-3 py-1.5">Band</th></tr></thead>
        <tbody>{COGNITIVE_SECTIONS.filter((s) => attempt.section_scores?.[s]).map((s) => {
          const sc = attempt.section_scores![s]; const pc = cohortPercentile(sc.pct, done.map((c) => c.section_scores?.[s]?.pct ?? 0));
          return <tr key={s} className="border-b border-[#DDDDDD]"><td className="px-3 py-1.5 font-semibold">{SECTION_LABELS[s]}</td><td className="text-center">{sc.correct}/{sc.total} ({sc.pct}%)</td><td className="text-center">{schedule.weights[s] ?? 0}%</td><td className="px-3"><div className="flex items-center gap-2"><Bar value={pc} /><span className="w-8 text-right">{pc}</span></div></td><td className="px-3">{band(pc)}</td></tr>;
        })}</tbody>
      </table>

      {attempt.trait_scores && Object.keys(attempt.trait_scores).length > 0 && <>
        <div className="text-[12px] font-bold uppercase tracking-[0.06em] border-b-2 border-[#EDC817] pb-1 mb-3">Personality profile</div>
        <div className="space-y-2.5 mb-2 text-[12px]">
          {Object.entries(TRAITS).filter(([t]) => attempt.trait_scores![t] !== undefined).map(([t, m]) => {
            const v = attempt.trait_scores![t];
            return <div key={t} className="grid grid-cols-[170px_1fr_40px] items-center gap-3"><div><div className="font-semibold">{m.label}</div><div className="text-[10px] text-[#6B6B6B]">{v >= 70 ? m.high : v <= 30 ? m.low : "balanced"}</div></div><Bar value={v} color={v <= 30 && m.lowIsRisk ? "#C27A06" : "#EDC817"} /><span className="text-right font-bold">{v}</span></div>;
          })}
        </div>
        <p className="text-[11px] mb-6 text-[#525252]">Deception (impression management) score: <strong className="text-black">{attempt.deception ?? 0}/6</strong>{(attempt.deception ?? 0) >= 4 ? " — high: the candidate may have presented themselves unrealistically; interpret the personality profile with caution." : " — within the normal range."}</p>
      </>}

      <div className="grid grid-cols-2 gap-4 mb-6 text-[12px]">
        <div className="border border-[#DDDDDD] rounded-[4px] p-3"><div className="font-bold mb-1.5 text-[#1B7A43]">Key strengths</div>{strengths.length ? <ul className="list-disc pl-4 space-y-1">{strengths.map((s) => <li key={s}>{s}</li>)}</ul> : <p className="text-[#6B6B6B]">No outstanding strengths identified.</p>}</div>
        <div className="border border-[#DDDDDD] rounded-[4px] p-3"><div className="font-bold mb-1.5 text-[#C27A06]">Development areas</div>{development.length ? <ul className="list-disc pl-4 space-y-1">{development.map((s) => <li key={s}>{s}</li>)}</ul> : <p className="text-[#6B6B6B]">No significant development areas identified.</p>}</div>
      </div>

      <div className="text-[12px] font-bold uppercase tracking-[0.06em] border-b-2 border-[#EDC817] pb-1 mb-3">Test integrity</div>
      <div className="grid grid-cols-4 gap-2 text-[11px] mb-2">
        {[["Left test window", attempt.focus_lost], ["Seconds away", attempt.time_away_seconds], ["Copy/paste attempts", attempt.copy_paste], ["Full-screen exits", attempt.fullscreen_exits]].map(([l, v]) => (
          <div key={l as string} className={`border rounded-[4px] p-2 text-center ${Number(v) > 0 ? "border-[#C27A06] bg-[#FDF3E0]" : "border-[#DDDDDD]"}`}><div className="text-[16px] font-bold">{v}</div><div className="text-[#6B6B6B]">{l}</div></div>))}
      </div>
      {(attempt.flags ?? []).length > 0 ? <ul className="text-[11px] text-[#C27A06] list-disc pl-4 mb-6">{attempt.flags!.map((f) => <li key={f}>{f}</li>)}</ul> : <p className="text-[11px] text-[#1B7A43] mb-6">No integrity concerns recorded.</p>}

      <div className="rounded-[4px] p-4 text-center" style={{ background: risk.bg, color: risk.fg }}>
        <div className="text-[11px] uppercase tracking-[0.08em] font-semibold">Overall recommendation</div>
        <div className="text-[18px] font-bold mt-1">{risk.label}</div>
        <div className="text-[11px] mt-1 opacity-80">Weighted cognitive score {attempt.weighted_score} · thresholds: recommended ≥ {schedule.low_risk_min}, moderate ≥ {schedule.moderate_min}</div>
      </div>
    </PrintFrame>
  );
}

// ====================== Consolidated (ranked) report ======================
export function ScheduleReport({ schedule, attempts, trainees, open, onClose }: { schedule: Schedule; attempts: AttemptSummary[]; trainees: Trainee[]; open: boolean; onClose: () => void }) {
  const byId = Object.fromEntries(trainees.map((t) => [t.id, t]));
  const done = attempts.filter((a) => a.status === "submitted").sort((a, b) => (b.weighted_score ?? 0) - (a.weighted_score ?? 0));
  const scores = done.map((a) => a.weighted_score ?? 0);
  const secs = COGNITIVE_SECTIONS.filter((s) => done.some((a) => a.section_scores?.[s]));
  const counts = { low: done.filter((a) => a.risk === "low").length, moderate: done.filter((a) => a.risk === "moderate").length, high: done.filter((a) => a.risk === "high").length };
  const notSat = attempts.filter((a) => a.status !== "submitted" && a.status !== "void");
  const avg = scores.length ? Math.round((scores.reduce((s, x) => s + x, 0) / scores.length) * 10) / 10 : 0;
  const topTrait = (a: AttemptSummary, hi: boolean) => {
    const e = Object.entries(a.trait_scores ?? {}).sort((x, y) => (hi ? y[1] - x[1] : x[1] - y[1]))[0];
    if (!e) return "—"; if (hi ? e[1] < 65 : e[1] > 35) return "No dominant traits";
    return `${TRAITS[e[0]]?.label ?? e[0]} (${e[1]})`;
  };

  const csv = () => {
    const head = ["Rank", "Surname", "First name", "Programme", "Institution", "Discipline", "Form", ...secs.map((s) => SECTION_LABELS[s] + " %"), "Weighted score", "Intake percentile", "Deception", "Strength", "Weakness", "Integrity flags", "Recommendation"];
    const rows = done.map((a, i) => { const t = byId[a.trainee_id]; return [i + 1, t?.surname, t?.first_name, TYPE_LABEL[t?.trainee_type ?? ""], t?.institution ?? "", t?.programme ?? "", a.form_code, ...secs.map((s) => a.section_scores?.[s]?.pct ?? ""), a.weighted_score, cohortPercentile(a.weighted_score ?? 0, scores), a.deception, topTrait(a, true), topTrait(a, false), (a.flags ?? []).join("; "), RISK_META[a.risk ?? "high"].short]; });
    const body = [head, ...rows].map((r) => r.map((v) => `"${String(v ?? "").replace(/"/g, '""')}"`).join(",")).join("\n");
    const el = document.createElement("a"); el.href = URL.createObjectURL(new Blob([body], { type: "text/csv" })); el.download = `${schedule.name.replace(/\W+/g, "_")}_ranked.csv`; el.click();
  };

  return (
    <PrintFrame id="schedule-report" title={`Consolidated report — ${schedule.name}`} landscape open={open} onClose={onClose} onCsv={csv}>
      <h1 className="text-[17px] font-bold tracking-wide uppercase">{schedule.name}: candidates ranked by overall performance</h1>
      <p className="text-[12px] text-[#525252] mb-4">{TYPE_LABEL[schedule.trainee_type]} · {done.length} assessed{notSat.length ? ` · ${notSat.length} not yet completed` : ""} · intake average {avg}</p>

      <div className="grid grid-cols-4 gap-3 mb-5">
        {(["low", "moderate", "high"] as const).map((r) => (
          <div key={r} className="rounded-[4px] p-3" style={{ background: RISK_META[r].bg, color: RISK_META[r].fg }}><div className="text-[22px] font-bold">{counts[r]}</div><div className="text-[11px] font-semibold">{RISK_META[r].label}</div></div>))}
        <div className="rounded-[4px] p-3 border border-[#DDDDDD]"><div className="text-[11px] font-semibold mb-1.5">Score distribution</div>
          <div className="flex items-end gap-1 h-[38px]">{[0, 20, 40, 60, 80].map((lo) => { const n = scores.filter((s) => s >= lo && (lo === 80 ? s <= 100 : s < lo + 20)).length; const max = Math.max(1, ...[0, 20, 40, 60, 80].map((l) => scores.filter((s) => s >= l && (l === 80 ? s <= 100 : s < l + 20)).length)); return <div key={lo} className="flex-1 bg-[#EDC817]" style={{ height: `${(n / max) * 100}%`, minHeight: n ? 3 : 0 }} title={`${lo}-${lo + 20}: ${n}`} />; })}</div>
          <div className="flex justify-between text-[9px] text-[#6B6B6B] mt-0.5"><span>0</span><span>50</span><span>100</span></div></div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-[10.5px] border border-[#DDDDDD]">
          <thead><tr className="bg-black text-white">
            <th className="px-1.5 py-1.5">#</th><th className="text-left px-1.5">Candidate</th><th className="text-left px-1.5">Programme / discipline</th>
            {secs.map((s) => <th key={s} className="px-1.5 leading-tight">{SECTION_LABELS[s].replace(" Reasoning", "").replace("Attention to Detail", "Detail").replace("Data Interpretation", "Data")}<div className="font-normal text-[#EDC817]">{schedule.weights[s] ?? 0}%</div></th>)}
            <th className="px-1.5">Weighted</th><th className="px-1.5">Pctl</th><th className="px-1.5">Dec.</th><th className="text-left px-1.5">Personality strength</th><th className="text-left px-1.5">Watch area</th><th className="px-1.5">Recommendation</th>
          </tr></thead>
          <tbody>{done.map((a, i) => { const t = byId[a.trainee_id]; const r = RISK_META[a.risk ?? "high"]; return (
            <tr key={a.id} className="border-b border-[#DDDDDD]" style={{ breakInside: "avoid" }}>
              <td className="text-center font-bold px-1.5 py-1">{i + 1}</td>
              <td className="px-1.5"><div className="font-semibold">{t?.surname}, {t?.first_name}</div>{(a.flags ?? []).length > 0 && <div className="text-[9px] text-[#C27A06]">⚑ {(a.flags ?? []).length} integrity flag(s)</div>}</td>
              <td className="px-1.5">{TYPE_LABEL[t?.trainee_type ?? ""]}<div className="text-[9px] text-[#6B6B6B]">{t?.programme ?? t?.institution ?? ""}</div></td>
              {secs.map((s) => <td key={s} className="text-center">{a.section_scores?.[s]?.pct ?? "—"}</td>)}
              <td className="text-center font-bold">{a.weighted_score}</td><td className="text-center">{cohortPercentile(a.weighted_score ?? 0, scores)}</td>
              <td className={`text-center ${(a.deception ?? 0) >= 4 ? "text-[#B91C1C] font-bold" : ""}`}>{a.deception}</td>
              <td className="px-1.5">{topTrait(a, true)}</td><td className="px-1.5">{topTrait(a, false)}</td>
              <td className="text-center px-1 font-semibold" style={{ background: r.bg, color: r.fg }}>{r.short}</td>
            </tr>); })}</tbody>
        </table>
      </div>

      <div className="mt-6 text-[12px]" style={{ breakInside: "avoid" }}>
        <div className="font-bold uppercase tracking-[0.06em] border-b-2 border-[#EDC817] pb-1 mb-2">Narration</div>
        {(["high", "moderate"] as const).map((r) => { const list = done.filter((a) => a.risk === r); if (!list.length) return null; return (
          <div key={r} className="mb-3"><div className="font-semibold" style={{ color: RISK_META[r].fg }}>{RISK_META[r].label}</div>
            <ul className="list-disc pl-5">{list.map((a) => { const t = byId[a.trainee_id]; const weak = COGNITIVE_SECTIONS.filter((s) => (a.section_scores?.[s]?.pct ?? 100) < 40).map((s) => SECTION_LABELS[s].toLowerCase()); return <li key={a.id}>{t?.full_name} — {r === "high" ? "low" : "moderate"} overall cognitive score ({a.weighted_score}){weak.length ? `; weakest in ${weak.join(", ")}` : ""}{(a.deception ?? 0) >= 4 ? "; high deception score" : ""}{(a.flags ?? []).length ? "; integrity flags recorded" : ""}.</li>; })}</ul></div>); })}
        {notSat.length > 0 && <p className="text-[#6B6B6B]">Not yet completed: {notSat.map((a) => byId[a.trainee_id]?.full_name).join(", ")}.</p>}
      </div>
    </PrintFrame>
  );
}
